### ISSUE TITLE
Meeup event poster design | May 22nd

### ISSUE THREAD

**Issue by nomadicmehul** [gdgnashik/OpenDesign#5]
## Goal: 
Poster for Meetup event and social media

## Info: 
Talk title: Using TensorFlow Hub to make better AI applications
Speaker details: https://docs.google.com/document/d/1E94LnsXZzdPVRxR2MlP4iOiGpzGs1Y6kmY2p4UOu8AM/edit
Event date: Friday 22nd May 8 pm

## Style Information: 
Use the GDG style guide and logo of GDG Nashik. Refer to the previous meetup event posters.

## Deadline: 

- [ ] May 17th 2020

**Comment by mpokar** [comment]
![GDG-NASHIK](https://user-images.githubusercontent.com/49711004/82150577-6ec21f00-9876-11ea-9256-4360967b964f.png)
Done

**Comment by mpokar** [comment]
![GDG-NASHIK](https://user-images.githubusercontent.com/49711004/82150795-b9dc3200-9876-11ea-920c-c465e59cf74e.png)

**Comment by nomadicmehul** [comment]
Thanks Mitesh.
