### ISSUE TITLE
Online Meetup | Poster Design | June 6th

### ISSUE THREAD

**Issue by nomadicmehul** [gdgnashik/OpenDesign#6]
## Goal: 
Need poster design for social media and youtube as per the respective size. 

## Info: 
Title: First look - Containers & Docker 
Speaker: Mehul Patel
Date & Time : 6th June & 6.00PM IST  
Add the "TechnoPanti" as community Partner 
Speaker DP: https://drive.google.com/file/d/1Vstfg3pLDdUDzlStq4HEY0QkRfhLK2aM/view?usp=sharing

## Style Information: 
Try the local theme, also need the GDG Nashik Layout for the presentation (This will use in future)

## Deadline: 
4th June 2020

**Comment by mpokar** [comment]
![s1](https://user-images.githubusercontent.com/49711004/83856727-a286bb00-a737-11ea-99dd-5d717f446167.png)

**Comment by mpokar** [comment]
[GDGNashik-Presentation_draft.pptx](https://github.com/gdgnashik/OpenDesign/files/4735022/GDGNashik-Presentation_draft.pptx)

Slide template

**Comment by nomadicmehul** [comment]
@mpokar We supposed to get this poster at least 2-3 days early. This time I am postponing for this event for next Saturday at same time. Kindly please make the changes and share it here. 

Thank you.

**Comment by internautsit** [comment]
![Desktop - 3](https://user-images.githubusercontent.com/66420790/83936248-7cb4f100-a7df-11ea-8f3a-24dd18214a16.png)

Noted!

**Comment by mpokar** [comment]
![Desktop - 3](https://user-images.githubusercontent.com/49711004/83936259-9f470a00-a7df-11ea-8d1a-d4a9e15ef722.png)

Noted!

**Comment by nomadicmehul** [comment]
Thanks, Mitesh.
