### ISSUE TITLE
Spaker Poster | Meetup event | Prachi Durge.

### ISSUE THREAD

**Issue by nomadicmehul** [gdgnashik/OpenDesign#8]
## Goal: 
Need the speaker poster for the GDG Nashik upcoming event

## Info: 
https://www.meetup.com/GDG-Nashik/events/271725964/

## Style Information: 
Add the GDG Nashik theme and android 11 themes. Try the mixture and make it accordingly. 

## Deadline: 
5th July 2020

**Comment by nomadicmehul** [comment]
![IMG_20191101_101125893](https://user-images.githubusercontent.com/11514627/86525484-5ac59180-bea5-11ea-91b4-aa574a9558bc.jpg)

**Comment by mpokar** [comment]
![Android11](https://user-images.githubusercontent.com/49711004/86530574-692ca100-bed7-11ea-9d32-c811345b6d2e.png)

**Comment by nomadicmehul** [comment]
Thanks Mitesh. :)
